paths:
  - 'astro'
  - 'src'
  - '.'
fileTypes:
  - 'md'
  - 'mdx'
  - 'js'
  - 'ts'
#links:
#  - old: 'https://github.com/vixshan/mina'
#    new: 'https://github.com/vixshan/amina'
githubUrls:
  types:
    - 'all' 
ignore:
  - 'https://github.com/Discordjs/discordjs'
  - 'https://github.com/saiteja-madha'
  - 'https://github.com/lavalink-devs/Lavalink'
  - 'https://github.com/Androz2091/discord-invites-tracker'