module.exports = {
  OWNER_IDS: [],
  PREFIX: "!",
  BOT_INVITE: "",
  DISCORD_INVITE: "",
  DEFAULT_LVL_UP_MSG: "{m}, You just advanced to **Level {l}**",
  IMAGE_API: "https://discord-js-image-manipulation.herokuapp.com",
  EMBED_COLORS: {
    BOT_EMBED: "0x068ADD",
    TRANSPARENT_EMBED: "0x36393F",
    SUCCESS_EMBED: "0x00A56A",
    ERROR_EMBED: "0xD61A3C",
    WARNING_EMBED: "0xF7E919",
  },
  EMOJIS: {
    ARROW: "❯",
    ARROW_BULLET: "»",
    CIRCLE_BULLET: "•",
    CUBE_BULLET: "❒",
    WHITE_DIAMOND_SUIT: "♢",
    TICK: "✓",
    X_MARK: "✕",
    CURRENCY: "₪",
    TICKET_OPEN: "🎫",
    TICKET_CLOSE: "🔒",
  },
  CACHE_SIZE: {
    GUILDS: 10,
    USERS: 1000,
    COUNTER: 10,
  },
  MESSAGES: {
    API_ERROR: "Unexpected Backend Error! Try again later or contact support server",
  },
};
