github: [vixshan, firtoz]
ko_fi: vikshan
patreon: vikshan
open_collective: # Replace with a single Open Collective username
liberapay: vikshan
otechie: vikshan
lfx_crowdfunding:
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
